#!/usr/bin/env bash
# Update dependencies
sudo apt update -y
sudo apt upgrade -y

# Install nginx
sudo apt install nginx -y
sudo service nginx start
sudo ufw 'Nginx HTTP'
# Modify the root html
echo "Hello World!" | sudo tee /var/www/html/index.html

# test nginx config
sudo nginx -t

sudo service nginx reload
